name: Build and publish mydocker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare image variables
        run: |
          # Image name used by this workflow. Change if you want a different image name.
          echo "IMAGE=mydocker" >> $GITHUB_ENV

          # Allow overriding full repository via a secret (e.g. username/mydocker or org/mydocker).
          if [ -n "${{ secrets.DOCKERHUB_REPOSITORY }}" ]; then
            echo "REPO=${{ secrets.DOCKERHUB_REPOSITORY }}" >> $GITHUB_ENV
          else
            echo "REPO=${{ secrets.DOCKERHUB_USERNAME }}/mydocker" >> $GITHUB_ENV
          fi

          echo "DATE_TAG=$(date -u +%Y%m%d)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: ./production
          file: ./production/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REPO }}:latest
            ${{ env.REPO }}:${{ env.DATE_TAG }}
