name: Build and publish mydocker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

# Ensure the GITHUB_TOKEN can publish packages
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare image variables
        run: |
          # Image name and repo for GHCR
          echo "IMAGE=builder" >> $GITHUB_ENV
          echo "REPO=ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/${IMAGE}" >> $GITHUB_ENV
          echo "DATE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image for smoke test (linux/amd64)
        uses: docker/build-push-action@v4
        with:
          context: ./production
          file: ./production/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/builder:latest
            ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/builder:${{ github.run_number }}

      - name: Smoke test image (PlatformIO version)
        run: |
          echo "Running smoke tests against loaded image"
          docker run --rm ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/builder:latest --version
          docker run --rm ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/builder:latest pio platform list || echo "platform list failed"

      - name: Push image (linux/amd64)
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: ./production
          file: ./production/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/builder:latest
            ghcr.io/${{ github.repository_owner }}/alteriom-docker-images/builder:${{ github.run_number }}
