name: Build and publish mydocker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image for smoke test (linux/amd64)
        uses: docker/build-push-action@v4
        with:
          context: ./production
          file: ./production/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/mydocker:latest
            ${{ secrets.DOCKERHUB_USER }}/mydocker:${{ github.run_number }}

      - name: Smoke test image (PlatformIO version)
        run: |
          echo "Running smoke tests against loaded image"
          docker run --rm ${{ secrets.DOCKERHUB_USER }}/mydocker:latest --version
          docker run --rm ${{ secrets.DOCKERHUB_USER }}/mydocker:latest pio platform list || echo "platform list failed"

      - name: Push image (linux/amd64)
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: ./production
          file: ./production/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/mydocker:latest
            ${{ secrets.DOCKERHUB_USER }}/mydocker:${{ github.run_number }}
